### ISSUE TITLE
Is static salt across many hosts a good practice?

### ISSUE THREAD

**Issue by moreati** [samdoran/demo-playbooks#2]
Thank you for speaking at Ansible Automate London today. One of the tasks in your slides caught my eye. Does using a static salt across many hosts like this make life easier for an attacker?

https://github.com/samdoran/demo-playbooks/blob/3cfd2b22a48277fac79c85c41a44cd693c84d78e/security/change-root-password.yml#L10-L13

I presume the aim of using a known salt is to ensure a CHANGED status for the task represents an actual password change, as opposed to can incidental hash change introduced by a random salt. Would this alternative suggested by https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hashing-filters, to seed the salt from the host name serve the same purpose?

```jinja
{{ 'secretpassword' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
```

**Comment by samdoran** [comment]
> Does using a static salt across many hosts like this make life easier for an attacker?

Yes. If the salts are the same and the hashes are the same, that means the password are the same. That would be useful information, though the attacker still needs to discern the password. If the salts are different but the passwords are the same, the attacker has no way of knowing.

I explained that caveat that in the talk (at least I meant to).

> I presume the aim of using a known salt is to ensure a CHANGED status for the task represents an actual password change...

Correct. If the purpose is to ensure all your systems have the new password, you must use a consistent salt in order to see which ones were changed or out of compliance.

> Would this alternative suggested by https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hashing-filters, to seed the salt from the host name serve the same purpose?

Absolutely. It's just too much to explain in that slide and doesn't help explain the concept of "you can pass a hash to this filter" any better so I went with a simpler example for educational purposes.

**Comment by moreati** [comment]
Thank you. Makes more sense in light of those constraints, and it hadn't occurred to me that the root_password variable might have a different value on each host.
